CREATE TABLE "card" (
	"card_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "card_card_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"deck_id" bigint NOT NULL,
	"front_content" text NOT NULL,
	"back_content" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "flash_card_deck" (
	"deck_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flash_card_deck_deck_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"deck_name" varchar(100) NOT NULL,
	"description" text,
	"is_public" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "study_session" (
	"session_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "study_session_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"deck_id" bigint NOT NULL,
	"score_percent" smallint NOT NULL,
	"date_completed" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "study_session_score_percent_range" CHECK ("study_session"."score_percent" >= 0 AND "study_session"."score_percent" <= 100)
);
--> statement-breakpoint
CREATE TABLE "users" (
	"user_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "card" ADD CONSTRAINT "card_deck_id_flash_card_deck_deck_id_fk" FOREIGN KEY ("deck_id") REFERENCES "public"."flash_card_deck"("deck_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flash_card_deck" ADD CONSTRAINT "flash_card_deck_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "study_session" ADD CONSTRAINT "study_session_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "study_session" ADD CONSTRAINT "study_session_deck_id_flash_card_deck_deck_id_fk" FOREIGN KEY ("deck_id") REFERENCES "public"."flash_card_deck"("deck_id") ON DELETE cascade ON UPDATE no action;